# Portable Local Redis Configuration Profile
bind 127.0.0.1
port 6379
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
loglevel notice
logfile ""
databases 16
always-show-logo no

# Snapshot parameters (saves memory states directly to your drive layout)
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb

# Crucial Relative Anchor: Keeps database dumps right inside the running directory!
dir "./"
